import { ModelManager } from '../model/modelManager';
import { PINNED_RESTRAINTS, StructuralNode, Section } from '../model/types';

/** Round a coordinate to 3 decimal places for stable Map key construction. */
const coordKey = (v: number) => Math.round(v * 1000) / 1000;

export interface SlabInput {
  id: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  vertices?: { x: number; y: number }[];
}

/**
 * Returns the ordered polygon corners of a slab.
 * Uses slab.vertices if present (polygon slab), otherwise builds the
 * four corners from x1/y1/x2/y2 (rectangular slab).
 */
function getSlabCorners(slab: SlabInput): { x: number; y: number }[] {
  if (slab.vertices && slab.vertices.length >= 3) return slab.vertices;
  return [
    { x: slab.x1, y: slab.y1 },
    { x: slab.x2, y: slab.y1 },
    { x: slab.x2, y: slab.y2 },
    { x: slab.x1, y: slab.y2 },
  ];
}

/**
 * Generates structural model from slab geometry:
 * 1. Creates nodes at slab corners (polygon-aware)
 * 2. Creates beams along slab edges (polygon-aware)
 * 3. Creates columns at nodes (as vertical frame elements)
 * 4. Creates area elements for slabs (polygon-aware)
 */
export function generateStructureFromSlabs(
  model: ModelManager,
  slabs: SlabInput[],
  beamSection: Section,
  columnSection: Section,
  slabThickness: number,
  columnHeight: number = 4
): {
  nodeMap: Map<string, StructuralNode>;
  slabNodeMap: Map<string, number[]>;
} {
  model.clearAutoGenerated();

  const nodeMap = new Map<string, StructuralNode>();
  const slabNodeMap = new Map<string, number[]>();

  // Step 1: Create nodes at all slab corners (polygon-aware)
  const cornerPoints = new Set<string>();
  for (const slab of slabs) {
    const corners = getSlabCorners(slab);
    for (const p of corners) {
      const key = `${coordKey(p.x)},${coordKey(p.y)}`;
      if (!cornerPoints.has(key)) {
        cornerPoints.add(key);
        const node = model.createNode(p.x, p.y, 0, PINNED_RESTRAINTS);
        nodeMap.set(key, node);
      }
    }
  }

  // Step 2: Create beams along slab edges (polygon-aware, avoiding duplicates)
  const edgeSet = new Set<string>();
  for (const slab of slabs) {
    const corners = getSlabCorners(slab);
    const n = corners.length;
    for (let i = 0; i < n; i++) {
      const a = corners[i];
      const b = corners[(i + 1) % n];
      const [px1, py1, px2, py2] = a.x < b.x || (a.x === b.x && a.y < b.y)
        ? [a.x, a.y, b.x, b.y] : [b.x, b.y, a.x, a.y];
      const edgeKey = `${coordKey(px1)},${coordKey(py1)}-${coordKey(px2)},${coordKey(py2)}`;
      if (!edgeSet.has(edgeKey)) {
        edgeSet.add(edgeKey);
        const nodeI = nodeMap.get(`${coordKey(px1)},${coordKey(py1)}`);
        const nodeJ = nodeMap.get(`${coordKey(px2)},${coordKey(py2)}`);
        if (nodeI && nodeJ) {
          model.createBeam(nodeI.id, nodeJ.id, beamSection.id, true);
        }
      }
    }
  }

  // Step 3: Create columns at each node (vertical elements)
  for (const [, node] of nodeMap) {
    const bottomNode = model.createNode(node.x, node.y, -columnHeight, {
      ux: true, uy: true, uz: true,
      rx: true, ry: true, rz: true,
    });
    model.createColumn(bottomNode.id, node.id, columnSection.id, true);
  }

  // Step 4: Create area elements for slabs (polygon-aware)
  for (const slab of slabs) {
    const corners = getSlabCorners(slab);
    const nodeIds: number[] = [];
    for (const p of corners) {
      const node = nodeMap.get(`${coordKey(p.x)},${coordKey(p.y)}`);
      if (node) nodeIds.push(node.id);
    }
    if (nodeIds.length >= 3) {
      model.createArea(nodeIds, slabThickness, true);
      slabNodeMap.set(slab.id, nodeIds);
    }
  }

  return { nodeMap, slabNodeMap };
}
